config/routes.rb
Rails.application.routes.draw do
  resources :center_names do
    get :load_center
    get :add_new_center
    get :find_center
   
  end
  resources :user_details do 
    get :approve_user, on: :member
  end
  resources :group_benefits
  resources :group_premia
  resources :branches do
    get :load_branch
  end
  devise_for :users
  resources :premium_rates
  
  resources :members do
    collection do
      post :import
    end
  end

  resources :coverages do
    get :selected, on: :member
    patch :sgyrt_submit, on: :member # This is a PATCH route
    patch :lppi_submit, on: :member
    # get :sgyrt_submit, on: :member # This is a GET route
    get :check_residency
    get :coverage_history
    get :coverage_premium_benefits
    get :individual_only
    get :group_only
    collection do
      get :loan
      get :renewal
    end
  end
  
  resources :dependents do
    get :age_validation
    collection do
      post :import
    end
  end

  resources :batches do
    get :unlisted_preview, on: :member
    get :batch_submit, on: :member
    get :batch_download, on: :member
    get :batch_preview, on: :member
    get :load_batch
    get :find_batch
    get :add_new_batch
    collection do
      post :import
    end
    member do 
      get :import_cov
    end
    # post :import_coverages, on: :member
  end


  resources :benefits
  resources :posts

  # resources :coverages do
  #   get :selected, on: :member
  # end

  #get 'pages/home'
  #get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/dependent.rb
class Dependent < ApplicationRecord
  validates_presence_of :last_name, :first_name, :middle_name, :birth_date, :relationship, :civil_status, :gender
  belongs_to :member
  has_one :dependent_coverage

  def to_s
    "#{last_name}" + ", " + "#{first_name}" + " " + "#{middle_name[0.1]}" + ". "
  end

  def full_name 
    "#{last_name.capitalize}" + ", " + "#{first_name.capitalize}" + " " + "#{middle_name[0.1]}" + ". "
  end

  def get_formatted_dbday
    bday = birth_date.strftime("%m/%d/%Y")
  end

  def compute_dependent_benefit(coverage, val)
    mmbr_type = ""
    coverage.residency = (coverage.effectivity.year * 12 + coverage.effectivity.month) - (member.date_membership.year * 12 + member.date_membership.month)

    rlship = self.relationship
    
    case rlship
    when "Spouse"
      mmbr_type = 'spouse'
    when "Child"
      mmbr_type = 'child'
    when "Parent"
      mmbr_type = 'parent'
    end

    if val == "gp"
      
      g_prm = GroupPremium.where('? between residency_floor and residency_ceiling', coverage.residency)
      group_premium = g_prm.find_by(member_type: "#{mmbr_type}", term: coverage.term).premium unless g_prm.nil?
      
      return group_premium
    
    else

      g_bnft = GroupBenefit.where('? between residency_floor and residency_ceiling', coverage.residency)
      group_benefit_id = g_bnft.find_by(member_type: "#{mmbr_type}").id
      
      return group_benefit_id

    end
  end

  def get_dependent_group_benefit
    #return dependent.dependent_coverage.group_benefit.life
  end

  def is_dep_age_valid
        
    age = ((Date.today - self.birth_date.to_date) / 365).round
    rel = self.relationship

    #raise "error"
    
    if ["spouse", "parent"].include?(rel.downcase) && (18..65).include?(age)
      return true
    elsif ["child", "sibling"].include?(rel.downcase) && (3..21).include?(age)
      return true
    else
      return false
    end

  end

  def get_age(effectivity)
    ((effectivity - self.birth_date.to_date) / 365).round
  end

  def current_age
    ((Date.today - self.birth_date.to_date) / 365).round
  end

  def self.get_dependents_index(admin, query, current_user)
    if query.present?
      if admin == true
        where("last_name LIKE ? OR first_name LIKE ?", "%#{query}%", "%#{query}%")
      else
        where(member: Member.where(branch_id: current_user.user_detail.branch_id).where("description LIKE ?", "%#{query}%"))
      end
    else
      if admin == true
        all
      else
        where(member: Member.where(branch_id: current_user.user_detail.branch_id))
      end
    end
  end


end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_dependent, only: %i[ show edit update destroy ]

  # GET /dependents or /dependents.json
  def index
    # if params[:query].present?
    #   @dependents = Dependent.where("last_name LIKE ?", "%#{params[:query]}%")
    # else
    #   @dependents = Dependent.all
    # end

    @dependents = Dependent.get_dependents_index(current_user.admin, params[:query], current_user)

  end

  # GET /dependents/1 or /dependents/1.json
  def show
   
  end

  # GET /dependents/new
  def new
    #@dependent = Dependent.new
    #pass member id parameter @ dependents
    @member = Member.find(params[:m])
    @dependent = @member.dependents.build
    if Rails.env.development?
      dummy_data
    end
  end

  def dummy_data 
    #@dependent.last_name = FFaker::Name.last_name
    @dependent.last_name = @member.last_name
    @dependent.first_name = FFaker::Name.first_name
    @dependent.middle_name = FFaker::Name.first_name[0]
  end
  # GET /dependents/1/edit
  def edit
  end

  # POST /dependents or /dependents.json
  def create
    #@dependent = Dependent.new(dependent_params)
    @member = Member.find(params[:m])
    @dependent = @member.dependents.build(dependent_params)

    if @dependent.valid?
      respond_to do |format|
        if @dependent.save
          format.html { redirect_to @member, notice: "Dependent was successfully created." }
          format.json { render :show, status: :created, location: @dependent }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @dependent.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependents/1 or /dependents/1.json
  def update
    respond_to do |format|
      if @dependent.update(dependent_params)
        format.html { redirect_to @member, notice: "Dependent was successfully updated." }
        format.json { render :show, status: :ok, location: @dependent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependents/1 or /dependents/1.json
  def destroy
    @dependent.destroy

    respond_to do |format|
      # format.html { redirect_to dependents_url, notice: "Dependent was successfully destroyed." }
      format.html { redirect_to @member, notice: "Dependent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    brn_id = current_user.user_detail.branch_id

    import_service = ImportService.new(:dependent,params[:file],brn_id)
    import_message = import_service.import
    # redirect_to dependents_path, notice: import_message
    if import_message.present? && import_message == "No file uploaded"
      flash[:notice] = "No file uploaded"
      redirect_to dependents_path
    else
      status_names = import_message.map do |r|
        lname = r["LASTNAME"].upcase
        fname = r["FIRSTNAME"].upcase
        mname = r["MI"].upcase
      end.compact 

      status_count = import_message.group_by { |message| message["STATUS"] }.map { |status, messages| [status, messages.size] }.to_h
      
      # raise "errors"

      flash_existing = status_count["Existing"]
      flash_uploaded = status_count["Uploaded"]

      flash_names = status_names.map { |status_names| "#{status_names}<br>" }.join
    
      flash[:notice] = "Import successful. <br><br> Existing :"+flash_existing.to_s+"<br> Uploaded :"+flash_uploaded.to_s
      redirect_to dependents_path
    end


  end

  def age_validation

    @bday = params[:dbday]
    @relation = params[:drelation]
    
    @dependent = Dependent.new(birth_date: @bday, relationship: @relation)
    @age_validity = @dependent.is_dep_age_valid
    @dpndt_age = @dependent.current_age

    respond_to do |format|
      format.json { render json: { bday: @bday, age: @dpndt_age, relation: @relation, validity: @age_validity } }
     end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependent
      @dependent = Dependent.find(params[:id])
      @member = @dependent.member
    end

    # Only allow a list of trusted parameters through.
    def dependent_params
      params.require(:dependent).permit(:member_id, :last_name, :first_name, :middle_name, :birth_date, :civil_status, :gender, :mobile_no, :email, :relationship, :suffix)
    end
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/views/dependents/_dependent.html.erb
<div id="<% dom_id dependent %>">
  <div class="row">
    
    <div class="col-lg-12">
      <div class="mt-4 p-5 bg-secondary text-white rounded" id="<%= dom_id dependent %>">
        <h1 class="text-truncate"><%= dependent.full_name %></h1>
        <div class="text-wrap fw-lighter">
          <strong>Birth date: </strong><%= "#{dependent.get_formatted_dbday} ("+"#{@member.compute_member_age(dependent.birth_date)})" %>
        </div>
        <div class="text-wrap fw-lighter"><strong>Civil status: </strong><%= dependent.civil_status %></div>
        <div class="text-wrap fw-lighter"><strong>Gender: </strong><%= dependent.gender %></div>
        <div class="text-wrap fw-lighter"><strong>Mobile no: </strong><%= dependent.mobile_no %></div>
        <div class="text-wrap fw-lighter"><strong>Email: </strong><%= dependent.email %></div>
        <div class="text-wrap fw-lighter">Relation: <strong>(<%= dependent.relationship.upcase %>)</strong></div>
      </div>
    </div>
    
    <% if dependent.dependent_coverage.present? %>
    <div class="col-lg-6">
      <div class="card-body">
        <table class="table table-striped table-bordered table-hover table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Coverage</th>
              <th>Premium</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th width="5%"><%= dependent.dependent_coverage.id %></th>
              <td>
                <% dependent_prem =  dependent.dependent_coverage.premium %>
                <div class="text-wrap fw-light text-muted">
                  <span class="badge bg-muted text-dark">
                    <small>
                      LIFE: &#8369; <%= to_curr(dependent.dependent_coverage.group_benefit.life) %> <br> 
                      ADD: &#8369; <%= to_curr(dependent.dependent_coverage.group_benefit.add) %> <br> 
                      BURIAL: &#8369; <%= to_curr(dependent.dependent_coverage.group_benefit.burial) %>
                    </small>
                  </span> 
                </div>
              </td>
              <td>
                <div class="text-wrap fw-light text-muted">
                  <span class="badge bg-muted text-dark">
                    <small>&#8369; <%= to_curr(dependent_prem) %></small>
                  </span> 
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <% else %>
     <h3 class="text-truncate">No record(s) found...</h3>
    <% end %>
   
  </div>
</div>
  <%# console %>

app/views/dependents/_form.html.erb
<%= simple_form_for(@dependent, url: url, method: meth) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  
  <div class="form-inputs" data-controller="search" data-search-url="<%= dependents_path() %>">
    <div class="row">
        <%= f.input :member_id, wrapper_html: { class: "col-md-4", hidden: "false" }, input_html: { data: { search_target: "memberID" } } %>
        <%= f.input :last_name, wrapper_html: { class: "col-md-4" }, input_html: { data: { search_target: "lnameInput" }  } %>
        <%= f.input :first_name, wrapper_html: { class: "col-md-4" } %>
        <%= f.input :middle_name, wrapper_html: { class: "col-md-4" } %>
        <div>
          <%= f.label :birth_date %>
          <%= f.date_field :birth_date, class: "ddate_pick", input_html: { data: { search_target: "dateInput" }  } %>
        </div>
        <%= f.input :relationship, collection: ['Spouse', 'Child', 'Parent', 'Sibling'], wrapper_html: { class: "col-md-4", data: { action: 'change->search#relation_select' } } %>
        <%= f.input :civil_status , collection: ['Single', 'Married', 'Widowed', 'Divorced'], include_blank: true, wrapper_html: { class: "col-md-4" } %>
        <%= f.input :gender , collection: [['Male','M'],['Female','F']], include_blank: true, wrapper_html: { class: "col-md-4" } %>
        <%= f.input :mobile_no, wrapper_html: { class: "col-md-6" } %>
        <%= f.input :email, wrapper_html: { class: "col-md-6" } %>
    </div>

    <div class="form-actions">
      <%= link_to '<i class="bi bi-arrow-bar-left"></i>'.html_safe, @member, class: "btn btn-secondary" %>
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
    
  </div>
<% end %>

app/views/dependents/_search_dependent.html.erb
<%= turbo_frame_tag "dependents" do %>
  <%= render dependent %>
<% end %>

app/views/dependents/edit.html.erb
<%
=begin
%>
<div class="card">
  <h5 class="card-header">Edit dependent</h5>
  <div class="card-body">
    <%= render "form", url: dependent_path(@dependent), meth: 'patch' %>
  </div>
</div>
<%
=end
%>
<%= render "members/remote_modal", title: "Edit Dependent Info" do %>
  <%# render @dependent, item: @item %>
<div class="card">
  <h5 class="card-header">Edit dependent</h5>
  <div class="card-body">
    <%= render "form", url: dependent_path(@dependent), meth: 'patch' %>
  </div>
</div>
<% end %>

app/views/dependents/index.html.erb
<%# content_tag :h1, "List of Dependents" %>

<div class="card mb-3">
  <div class="card-header">Dependent Module</div>
  <div class="card-body">
      <div class=" row">
        <div class="col-lg-4"></div>
        <!--Upload Member-->
        <div class="col-lg-4">
        <%= form_with url: import_dependents_path, method: :post do |form| %>
          <%= form.label :file, "For member enrollment upload your csv file.", class: "form-text" %>
            <div class="d-flex gap-3">
              <%= form.file_field :file, class: "form-control", style: "width: 80%" %>
              <%= submit_tag 'Upload', class: "btn btn-primary btn-sm" %>
            </div>
          <% end %>
        </div>
        <!--Upload Member-->
        <div class="col-lg-4"></div>
      </div> 
    </div>     
</div>

<div class="container mt-3">
  <div class="row">
    <!--Search-->
    <div class="col-lg-12">
      <%= form_with( url: dependents_path, method: :get, data: {turbo_frame: "search_dependent"} ) do |form| %>
      <div class="input-group mb-3">
        <%= link_to '<i class="bi bi-arrow-bar-left"> Add Member</i>'.html_safe, members_path, class: "btn btn-secondary" %>
        <%= form.text_field :query, placeholder: 'Search by last name...', class: "form-control" %>
        <%= form.submit 'Search', class: "btn btn-success" %>
        <!--Add Dependent--
        <%#= link_to new_dependent_path, hidden: true, class: 'btn btn-primary' do %>
          New Dependent
        <%# end %>
        --Add Dependent-->
      </div>
      <% end %>
    </div>
    <!--Search-->
    <!--table-dependent-->
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Principal</th>
          <th>Dependent Info</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% dpdntcount = 0 %>
        <% @dependents.each do |dependent| %>
          <% dpdntcount += 1 %>
          <tr>
            <th scope="row"><%= dpdntcount %></th>
            <td><%= dependent.member.get_cmember %></td>
            <td>
              <div class="text-wrap fw-lighter">Name: <strong><%= dependent %></strong></div>
              <div class="text-wrap fw-lighter">Birth Date: <%= dependent.get_formatted_dbday %></div>
              <div class="text-wrap fw-lighter">Relation: <%= dependent.relationship %></div>
            </td>
            <td>
              <%= link_to 'View', dependent, class: 'btn btn-secondary btn-sm', data: { turbo_frame: "remote_modal"} %>
              <%= link_to 'Edit', edit_dependent_path(dependent), class: 'btn btn-secondary btn-sm', data: { turbo_frame: "remote_modal"} %>
              <%= link_to "Delete", dependent, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <!--table-dependent-->
  </div>
</div>  
<%# console %>

app/views/dependents/new.html.erb
<div class="card">
  <h5 class="card-header">New dependent</h5>
  <div class="card-body">
    <%# render "form", dependent: @dependent %>
    <%= render "form", url: dependents_path(m: @member), meth: 'post' %>
  </div>
</div>

app/views/dependents/show.html.erb
<%# render @dependent %>
<%
=begin
%>
<div>
  <%= link_to "Edit", edit_dependent_path(@dependent), class: 'btn btn-primary' %> |
  <%= link_to "Back", @member, class: 'btn btn-primary' %>

  <%= button_to "Delete", @dependent, method: :delete, class: 'btn btn-danger' %>
</div>
<%
=end
%>
<%= render "members/remote_modal", title: "Dependent Info" do %>
  <%= render @dependent, item: @item %>
<% end %>