config/routes.rb
Rails.application.routes.draw do
  resources :center_names do
    get :load_center
    get :add_new_center
    get :find_center
   
  end
  resources :user_details do 
    get :approve_user, on: :member
  end
  resources :group_benefits
  resources :group_premia
  resources :branches do
    get :load_branch
  end
  devise_for :users
  resources :premium_rates
  
  resources :members do
    collection do
      post :import
    end
  end

  resources :coverages do
    get :selected, on: :member
    patch :sgyrt_submit, on: :member # This is a PATCH route
    patch :lppi_submit, on: :member
    # get :sgyrt_submit, on: :member # This is a GET route
    get :check_residency
    get :coverage_history
    get :coverage_premium_benefits
    get :individual_only
    get :group_only
    collection do
      get :loan
      get :renewal
    end
  end
  
  resources :dependents do
    get :age_validation
    collection do
      post :import
    end
  end

  resources :batches do
    get :unlisted_preview, on: :member
    get :batch_submit, on: :member
    get :batch_download, on: :member
    get :batch_preview, on: :member
    get :load_batch
    get :find_batch
    get :add_new_batch
    collection do
      post :import
    end
    member do 
      get :import_cov
    end
    # post :import_coverages, on: :member
  end


  resources :benefits
  resources :posts

  # resources :coverages do
  #   get :selected, on: :member
  # end

  #get 'pages/home'
  #get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/coverage.rb
class Coverage < ApplicationRecord
  attr_accessor :button_name

  belongs_to :batch
  # belongs_to :member, optional: true
  belongs_to :member
  belongs_to :group_benefit, optional: true
  has_many :dependent_coverages, dependent: :destroy
  belongs_to :center_name
  # validates_presence_of :member_id, :loan_certificate, :effectivity, :term, :grace_period, :status
  validates_presence_of :member_id, :loan_certificate, :effectivity, :term, :status
  # validates :grace_period, numericality: { only_integer: true }
  validates :loan_coverage, numericality: { greater_than: 0 }, if: :member_button_pressed?

  TERMS = [3, 4, 5, 6, 9, 12, 18, 24, 30, 36]

  def compute_age
    # Get age using excel format ((bday-efdate) / 365)
    age_in_days = (effectivity - member.birth_date).to_i
    # age_in_years = (age_in_days / 365.0).floor
    age_in_years = (age_in_days / 365.0).round # Used .round instead of .floor for float data_type to the nearest (ex age = 70.6 to 71)
    self.age = age_in_years

    # SET PREMIUM RATE ACCORDING TO AGE group/range

    case age 
    when 18..65
      self.rate = 0.83
    when 66..70
      self.rate = 3
      self.rate = 4 if loan_coverage > 350000
    when 71..75 
      self.rate = 4
      self.rate = 5 if loan_coverage > 350000
    when 76..80
      self.rate = 5
      self.rate = 8.75 if loan_coverage > 350000
    end
    
    #GET EXPIRY BASED ON EFFECTIVITY AND TERM
    self.expiry = effectivity >> term # Shift (forward) selected date by the no. of terms 
    # raise "errors"
    case grace_period
      when 0
        self.loan_premium = ((loan_coverage/1000)*(rate*12)/12*term)
        self.loan_premium = ((loan_coverage/1000)*((10.to_f/12).round(3)*12)/12*term) if rate == 0.83 #rate = (10/12) gives 0.833 instead of 0.83
        # self.loan_premium = round_to_nearest(loan_premium, 0.05)
      else
        self.expiry = expiry + grace_period
        self.loan_premium = ( (loan_coverage/1000) * (rate * (term + grace_period) ) )
      end
      
    # self.residency = (effectivity.year * 12 + effectivity.month) - (member.date_membership.year * 12 + member.date_membership.month)
    # self.residency = member.coverages.sum(:term)

    gp = GroupPremium.where('? between residency_floor and residency_ceiling', self.residency)
    self.group_premium = gp.find_by(member_type: 'principal', term: self.term).premium unless gp.nil?

    gb = GroupBenefit.where('? between residency_floor and residency_ceiling', self.residency)
    self.group_benefit_id = gb.find_by(member_type: 'principal').id
    
  end
  
  def compute_group_only
    age_in_days = (effectivity - member.birth_date).to_i
    age_in_years = (age_in_days / 365.0).round
    self.age = age_in_years

    self.expiry = effectivity >> term
    self.expiry = expiry + grace_period
      
    gp = GroupPremium.where('? between residency_floor and residency_ceiling', self.residency)
    self.group_premium = gp.find_by(member_type: 'principal', term: self.term).premium unless gp.nil?

    gb = GroupBenefit.where('? between residency_floor and residency_ceiling', self.residency)
    self.group_benefit_id = gb.find_by(member_type: 'principal').id
    
  end

  def coverage_aging
    today = Date.today
    #c_aging = ((exdate.to_date - efdate.to_date) / 31).round
    #self.term = c_aging

    if expiry.present? && effectivity.present?
      # ((expiry.to_date - effectivity.to_date) / 31).round? Month
      aging = ((expiry - today)).round
      if aging <= 0
        return aging = 0
      else
        return aging
      end
    end
  end

  def coverage_date
    cv_efdate = effectivity.strftime("%m/%d/%Y") 
    cv_exdate = expiry.strftime("%m/%d/%Y")
    "#{cv_efdate}"+ " - " + "#{cv_exdate}"
  end

  def coverage_status
    vstatus = ""
    if status == "N"
      vstatus = "New"
    else
      vstatus = "Renewal"
    end
  end

  def coverage_aging_status(val)
    if val <= 0
      return "Expired"
    else
      return "#{val} day(s)"
    end
  end

  def self.get_coverages_index(admin, query, current_user)
    if query.present?
      if admin == true
        # find_by(member: Member.where("last_name LIKE ? OR first_name LIKE ?", "%#{query}%", "%#{query}%"))
        where(member: Member.where("last_name LIKE ?", "%#{query}%"))
      else
        # where(branch_id: current_user.user_detail.branch_id).where("last_name LIKE ? OR first_name LIKE ?", "%#{query}%", "%#{query}%")
        where(member: Member.where("last_name LIKE ? OR first_name LIKE ?", "%#{query}%", "%#{query}%").where(branch_id: current_user.user_detail.branch_id))
      end
    else
      where(member: Member.where(branch_id: current_user.user_detail.branch_id))
    end
  end

  def round_to_nearest(value, nearest)
    (value / nearest).round * nearest
  end

  def coverage_lppi_premium
    # lppi_prem = batch.premium_rate.premium
    # if lppi_gross_coverage.present? && term.present?
    #   ((lppi_gross_coverage / 1000) * (term * lppi_prem))
    # end
  end

  def get_group_life
    #return coverage.group_benefits.life
  end

  def smcvg_idependent
    sum_dinsured = 0
      dependent_coverages.each do |dcvg|
        sum_dinsured += dcvg.group_benefit.life
      end
    return sum_dinsured
  end

  # def alpharray(val)
  #   numalpha = Array["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
  #   return numalpha[val-1]
  # end

  private

  def member_button_pressed?
    button_name == 'memberBtn'
  end

end

app/controllers/coverages_controller.rb
class CoveragesController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_coverage, only: %i[ show edit update destroy sgyrt_submit lppi_submit ]

  include Pagy::Backend
  # GET /coverages or /coverages.json
  def index

    require 'pagy/extras/bootstrap'
    
    # @ccoverages = Coverage.all
    @coverages = Coverage.get_coverages_index(current_user.admin, params[:query], current_user)
    # raise "errors"

    # if params[:query].present? == true
    #   @cntcvg = Coverage.get_coverages_index(current_user.admin, params[:query]=nil, current_user)
    # else
    #   @cntcvg = @coverages
    # end

    # @cn_exp_cvg = 0
    # @cn_act_cvg = 0
    
    # @cntcvg.each do |ccvg|
      
    #   chk_cvg = Coverage.where(member_id: ccvg.member_id)
    #   ret_cvg = chk_cvg.order(:effectivity,:expiry).last
    #   cov_aging = ret_cvg.coverage_aging

    #   cn_aging = cov_aging
    #   if cn_aging <= 0
    #     @cn_exp_cvg += 1
    #   elsif
    #     @cn_act_cvg += 1  
    #   end
    # end

    #set pagination 
    @pagy, @coverages = pagy(@coverages, items: 25)

  end

  # GET /coverages/1 or /coverages/1.json
  def show
    @actvID = params[:activeID]
    @actvPlan = params[:plan]
    @actvAge = params[:age]
  end
  
  # GET /coverages/new
  def new
    ###@coverage = Coverage.new
    # @batch = Batch.find(params[:b])
    # @coverage = @batch.coverages.build

    @bId = params[:b]
    @cId = params[:c]
    @mId = params[:m]

    if @bId.present? == true
      @batch = Batch.find(params[:b])
      @coverage = @batch.coverages.build
    elsif @mId.present? == true
      @member = Member.find(params[:m])
      @coverage = @member.coverages.build
      chk_cvg = Coverage.where(id: @cId)
      ret_cvg = chk_cvg.order(:effectivity,:expiry).last
      @get_cvg_sts = ret_cvg.status
    end

    # raise "errors"

    dummy_data
  end

  def dummy_data 
    @coverage.loan_certificate = rand(100000..999999)
    @coverage.group_certificate = rand(100000..999999)
    @coverage.effectivity = Date.current
  end

  # GET /coverages/1/edit
  def edit
  end

  def selected
    # @members = Member.where(id: params[:id])
    @target = params[:categoryId]
    respond_to do |format|
    format.turbo_stream
    # format.json { render json: @coverage.errors, status: :unprocessable_entity }
    end
  end

  # POST /coverages or /coverages.json
  def create
    if params[:b].present? == true
      @batch = Batch.find(params[:b])
      @coverage = @batch.coverages.build(coverage_params)
    elsif params[:m].present? == true
      @member = Member.find(params[:m])
      @coverage = @member.coverages.build(coverage_params)
    end
    
    @coverage.button_name = params.keys.find { |key| key.end_with?('Btn') }

    if params[:memberBtn]
      if @coverage.valid?
        @coverage.compute_age
        respond_to do |format|
          if @coverage.save
            verify_plan(@coverage)
            if @member.present? == true  
              format.html { redirect_to batch_url(@coverage.batch_id, qry: 0, pln: 0, pth: "b1"), notice: "Coverage was successfully created." }
            else    
              format.html { redirect_to batch_url(@batch, qry: 0, pln: 0, pth: "b1"), notice: "Coverage was successfully created." }
            end
            format.json { render :show, status: :created, location: @coverage }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @coverage.errors, status: :unprocessable_entity }
            format.turbo_stream { render :form_update, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @coverage.errors, status: :unprocessable_entity }
          format.turbo_stream { render :form_update, status: :unprocessable_entity }
        end
      end
    
    elsif params[:lppiBtn]  
        # code for saving coverage with lppi button
    elsif params[:sgyrtBtn]  
        # code for saving coverage with sgyrt button
    end

  end

  # PATCH/PUT /coverages/1 or /coverages/1.json
  def update

    # @coverage.age = @coverage.compute_age 
    # @coverage.term = @coverage.coverage_aging
    # @coverage.lppi_gross_premium = @coverage.coverage_lppi_premium
    
    @coverage.compute_age
    respond_to do |format|
      if @coverage.update(coverage_params)
        format.html { redirect_to batch_url(@batch, qry: 0, pln: 0, pth: "b1"), notice: "Coverage was successfully updated." }
        format.json { render :show, status: :ok, location: @coverage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coverage.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /coverages/1 or /coverages/1.json
  def destroy
   @dplan = params[:plan]
   @dage = params[:age]
    # raise "errors"
    @coverage.destroy
    respond_to do |format|
      format.html { redirect_to batch_url(@batch, qry: @dage, pln: @dplan, pth: "b1"), notice: "Coverage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def check_residency
    @mmbrID = params[:Id]
    
    @check_coverage = Coverage.where(member_id: @mmbrID)
    
    if @check_coverage.empty? == true
        render json: {
          mmbrID: @mmbrID,
          residency: 0,
          status: 0,
          count_id: 0,
          coverage: 0,
          redirecto: member_path(@mmbrID)
        }
    else
      @count_coverage = @check_coverage.where(member_id: @mmbrID).count
      @sum_residency = @check_coverage.sum(:term)
    
      # Sort record base on terms and retrieve the latest record (1 record)
      @retrieve_coverage = @check_coverage.order(:effectivity,:expiry).last
      @cov_aging = @retrieve_coverage.coverage_aging

      @cov_status = @retrieve_coverage.status
      @member_link = member_path(@mmbrID)

      render json: { 
        mmbrID: @mmbrID, 
        residency: @sum_residency, 
        status: @cov_status, 
        count_id: @count_coverage, 
        coverage: @cov_aging, 
        redirecto: @member_link 
      }
       
    end
    
  end

  def coverage_history
    
    @target = params[:target]
    @chkCoverage = Coverage.where(member_id: params[:Id])
    # raise "errors"

    if @chkCoverage.empty? == true
      render turbo_stream: [ turbo_stream.update(@target, partial: "coverages/show_prev_loan", locals: { rCvg: nil }) ]
    else
      @rtrCoverage = @chkCoverage.order(:effectivity, :expiry).last
      # format.turbo_stream show output to "coverage_history.turbo_stream.erb"
      render turbo_stream: [ turbo_stream.update(@target, partial: "coverages/show_prev_loan", locals: { rCvg: @rtrCoverage }) ]
    end

  end

  def coverage_premium_benefits
    @ptarget = params[:ptarget]
    @pId = params[:Id]
    @eDate = params[:efdate]
    @pterm = params[:term]
    @rsdncy = params[:residency]
    @pgp = params[:gperiod]
    @ploans = params[:loans]

    # @getMember = Member.find(@pId)
    @coveragePremiumBenefits = Coverage.new(member_id: @pId, effectivity: @eDate, term: @pterm, residency: @rsdncy, grace_period: @pgp, loan_coverage: @ploans)
    @coveragePremiumBenefits.compute_age
    # raise "error"

    render turbo_stream: [ turbo_stream.update(@ptarget, partial: "coverages/show_premium", locals: { sCvg: @coveragePremiumBenefits }) ]

  end

  def individual_only
    # /coverages/${comboMember}/individual_only/?cmember=${comboMember}&cbatch=${tBatch}&ccenter=${comboCenter}&icert=${indCert}&edate=${eDate}&residency=${textResidency}&cstatus=${textStatus}&cterm=${textTerm}&gperiod=${textGracePeriod}&loansamount=${textLoan}
    mId = params[:cmember]
    bId = params[:cbatch]
    cId = params[:ccenter]
    indCert = params[:icert]
    cEdate = params[:edate]
    residency = params[:residency]
    cStats = params[:cstatus]
    cTerm = params[:cterm]
    gpreriod = params[:gperiod]
    tLoan = params[:loansamount]

    @coverageGroupOnly = Coverage.new(member_id: mId, batch_id: bId, loan_certificate: indCert, effectivity: cEdate, residency: residency, status: cStats, term: cTerm, grace_period: gpreriod, center_name_id: cId, loan_certificate: 0, loan_coverage: tLoan, rate: 0, plan_lppi: true, plan_sgyrt: false)
    @coverageGroupOnly.compute_age
    @coverageGroupOnly.save
    verify_plan_group_only(@coverageGroupOnly)

    render json: { 
      mmbrID: mId, 
      residency: residency, 
      pstatus: @coverageGroupOnly.persisted?
    }
    
  end

  def group_only
    # cmember=${comboMember}&ccenter=${comboCenter}&gcert=${groupCert}&residency=${textResidency}&cstatus=${textStatus}&cterm=${textTerm}&gperiod=${textGracePeriod}
    mId = params[:cmember]
    bId = params[:cbatch]
    cId = params[:ccenter]
    groupCert = params[:gcert]
    cEdate = params[:edate]
    residency = params[:residency]
    cStats = params[:cstatus]
    cTerm = params[:cterm]
    gpreriod = params[:gperiod]
    
    @coverageGroupOnly = Coverage.new(member_id: mId, batch_id: bId, group_certificate: groupCert, effectivity: cEdate, residency: residency, status: cStats, term: cTerm, grace_period: gpreriod, center_name_id: cId, loan_certificate: 0, loan_premium: 0, loan_coverage: 0, rate: 0, plan_lppi: false, plan_sgyrt: true)
    @coverageGroupOnly.compute_group_only
    @coverageGroupOnly.save
    verify_plan_individual_only(@coverageGroupOnly)

    render json: { 
      mmbrID: mId, 
      residency: residency, 
      pstatus: @coverageGroupOnly.persisted?
    }
  end

  def verify_plan(arr)
    lppi_status = arr.member.plan_lppi
    sgyrt_status = arr.member.plan_sgyrt
    
    if lppi_status == true && sgyrt_status == true
      # return "dependent save"
      dependent_coverage_save
    elsif lppi_status == true && sgyrt_status == false
      arr.update(plan_sgyrt: 0)
      arr.dependent_coverages.destroy_all

app/helpers/coverages_helper.rb
module CoveragesHelper

  # def compute_cvg_member_age(bday)
  #   today = Date.today
  #   cm_age = ((today - bday.to_date) / 365).round
  # end

  def service_fee(p)
    sfee = 0 
    case p 
    when "0"
      sfee = 0  
    when "1865" 
      sfee = 0.1
    when "6670"
      # self.rate = 3
      # self.rate = 4 if loan_coverage > 350000
    when "7175" 
      # self.rate = 4
      # self.rate = 5 if loan_coverage > 350000
    when "7680"
      # self.rate = 5
      # self.rate = 8.75 if loan_coverage > 350000
    end
    return sfee
  end

end

app/views/coverages/_search_renewal.html.erb
<%= turbo_frame_tag "cvg_renewal" do %>
  <%= render coverage %>
<% end %>

app/views/coverages/edit.html.erb
<%= render "remote_modal", title: "Edit Loan" do %>
  <%= render "form", url: coverage_path(@coverage), meth: 'patch' %>
<% end %>

app/views/coverages/index.html.erb
<%# content_tag :h1, "List of Loans x(#{@cn_act_cvg})" %>
<%= content_tag :h1, "List of Loans (Individual)" %>
  <!--Search-->
    <div class="col-lg-12">
      <%= form_with( url: coverages_path, method: :get, data: {turbo_frame: "search_loan"} ) do |form| %>
      <div class="input-group mb-3">
        <%= form.text_field :query, placeholder: 'Search by last name...', class: "form-control" %>
        <%= form.submit 'Search', class: "btn btn-success" %>
        <!--Renewal-Btn-->
         <%= link_to renewal_coverages_path, data: { turbo_method: :get }, class: 'btn btn-primary position-relative' do %>
            Renewals
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
              <%= @cn_exp_cvg %>
            </span>
          <% end %>
        <!--Renewal-Btn-->
      </div>
      <% end %>
      <%== pagy_bootstrap_nav(@pagy) %>
      <%#== pagy_info(@pagy) %>
    </div>
  <!--Search-->
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="text-center">ID</th>
        <th>Insured</th>
        <th>Loan Data</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% 
        cmember = ""
        cbdate = ""
        cterm = 0
        cvgcount = 0
        @coverages.each do |coverage| 
          chk_cvg = Coverage.where(member_id: coverage.member_id)
          ret_cvg = chk_cvg.order(:effectivity, :expiry).last
          cov_aging = ret_cvg.coverage_aging
          
          cn_aging = cov_aging
          if cn_aging > 0
            cvgcount += 1
            cbatch = coverage.batch.title
            crate = coverage.rate
            cmember = coverage.member.get_cmember
            # cbdate = coverage.member.get_formatted_bday
            # c_age = coverage.member.compute_member_age(coverage.member.birth_date)
            cterm = ret_cvg.term
            csuninsurge = ret_cvg.loan_coverage
            cpremium = ret_cvg.loan_premium
      %>
        <tr id="cvg_loan">
          <th scope="row" class="text-center"><%= coverage.id %><%# "#{coverage.id}"+" - #{cvgcount}" %><%# cvgcount %></th>
          <td>
            <div class="badge bg-primary text-wrap" style="width: 6rem;"><%= coverage.loan_certificate %></div>
            <div class="text-wrap fw-lighter"><strong><%= cmember.upcase %></strong></div>
            <!--
            <div class="text-wrap fw-lighter">Birth Date: <%# cbdate %></div>
            <div class="text-wrap fw-lighter">Age: <%# c_age %></div>
            -->
          </td>
          <td>
            <div class="badge bg-primary text-wrap" style="width: 10rem;"><%= ret_cvg.coverage_date %></div>
            <div class="badge bg-primary text-wrap" style="width: 2rem;"><%= cterm %></div>
            <div class="badge bg-primary text-wrap" style="width: 4rem;"><%= coverage.coverage_status %></div>
            <% if cn_aging <= 0 %>
            <div class="badge bg-danger text-wrap" style="width: 4rem;"><%= coverage.coverage_aging_status(cn_aging) %></div>
            <% else %>
            <div class="badge bg-primary text-wrap" style="width: 6rem;"><%= coverage.coverage_aging_status(cn_aging) %></div>
            <% end %>
            <div class="text-wrap fw-lighter"><small>Coverage: <%= cbatch %></small></div>
            <div class="text-wrap fw-lighter"><small>Sum Insured: <%= csuninsurge %></small></div>
            <div class="text-wrap fw-lighter"><small>Premium: <%= cpremium %></small></div>
            <div class="text-wrap fw-lighter"><small>Rate: <%= crate %></small></div>
          </td>   
          <td>
            <%= link_to 'View', coverage_path(coverage, activeID: nil), class: 'btn btn-secondary btn-sm', data: {turbo_frame: "remote_modal"} %>
            <%# link_to 'Edit', edit_coverage_path(coverage), class: 'btn btn-secondary btn-sm' %>
            <%# link_to "Delete", coverage, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          </td>

        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

app/views/coverages/new.html.erb
<%# "(#{current_user.user_detail.last_name}"+" | #{current_user.email})" %>
<%# "BatchID: #{@bId}"+" MemberID: #{@mId}" %>
<%= render "remote_modal", title: "New Loan" do %>
  <% if @bId.present? == true %>
    <%= render "form", url: coverages_path(b: @batch), meth: 'post' %>
  <% elsif @mId.present? == true %>
    <%= render "form", url: coverages_path(m: @member), meth: 'post' %>
  <% end %>
<% end %>

app/views/coverages/renewal.html.erb
<%= content_tag :h1, "Renewals" %>
<%# @coverages.size %>
<!--Search-->
    <div class="col-lg-12">
      <%= form_with( url: renewal_coverages_path, method: :get, data: {turbo_frame: "search_renewal"} ) do |form| %>
      <div class="input-group mb-3">
      <% if @rse_params.present? == true %>
        <%= link_to '<i class="bi bi-arrow-repeat"></i>'.html_safe, renewal_coverages_path, class: "btn btn-secondary" %>
      <% else %>
         <!--Back-Btn-->
         <%= link_to loan_coverages_path, data: { turbo_method: :get }, class: 'btn btn-secondary position-relative' do %>
            <i class="bi bi-arrow-bar-left"></i>
      <% end %>
        <!--Back-Btn-->
        <% end %>
        <%= form.text_field :query, placeholder: 'Search by last name...', class: "form-control" %>
        <%= form.submit 'Search', class: "btn btn-success" %>
      </div>
      <% end %>
      <%== pagy_bootstrap_nav(@pagy) %>
      <%== pagy_info(@pagy) %>
    </div>
<!--Search-->
<div>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <!--<th class="text-center"></th>-->
        <th class="text-center">#</th>
        <th>Insured</th>
        <th>Loan Data</th>
        <th>action</th>
      </tr>
    </thead>
    <tbody>
      <% 
        cmember = ""
        cbdate = ""
        cterm = 0
        cvgcount = 0
        @cvg_renewal.each do |coverage| 
          # chk_cvg = Coverage.where(member_id: coverage.member_id)
          # ret_cvg = chk_cvg.order(:effectivity,:expiry).last
          cov_aging = coverage.coverage_aging

          cn_aging = cov_aging
            cvgcount += 1
            cbatch = coverage.batch.title
            crate = coverage.rate
            cmember = coverage.member.get_cmember
            cterm = coverage.term
            csuninsurge = coverage.loan_coverage
            cpremium = coverage.loan_premium
      %>
        <tr id="cvg_renewal">
          <!--<th class="text-center"><input class="form-check-input" id="#" name="#" type="checkbox" value="<%# coverage.member_id %>" disabled></th>-->
          <th scope="row" class="text-center"><%= coverage.id %><%# "#{coverage.id}"+" - #{cvgcount}" %><%# cvgcount %></th>
          <td>
            <div class="badge bg-primary text-wrap" style="width: 6rem;"><%= coverage.loan_certificate %></div>
            <div class="text-wrap fw-lighter"><strong><%= cmember.upcase %></strong></div>
          </td>
          <td>
            <div class="badge bg-primary text-wrap" style="width: 10rem;"><%= coverage.coverage_date %></div>
            <div class="badge bg-primary text-wrap" style="width: 2rem;"><%= cterm %></div>
            <div class="badge bg-primary text-wrap" style="width: 4rem;"><%= coverage.coverage_status %></div>
            <div class="badge bg-danger text-wrap" style="width: 4rem;"><%= coverage.coverage_aging_status(cn_aging) %></div>
            <div class="text-wrap fw-bold text-muted"><small><%= cbatch %></small></div>
            <!--
            <div class="text-wrap fw-lighter"><small>Sum Insured: <%#= csuninsurge %></small></div>
            <div class="text-wrap fw-lighter"><small>Premium: <%#= cpremium %></small></div>
            <div class="text-wrap fw-lighter"><small>Rate: <%#= crate %></small></div>
            -->
          </td>   
          <td>
            <%# link_to 'View', coverage_path(coverage), class: 'btn btn-secondary btn-sm' %>
            <%# link_to 'Edit', edit_coverage_path(coverage), class: 'btn btn-secondary btn-sm' %>
            <%# link_to "Delete", coverage, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
            <%= link_to "Renew", new_coverage_path(m: coverage.member_id, c: coverage.id), class: "btn btn-primary btn-sm", data: { turbo_frame: "remote_modal" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>