config/routes.rb
Rails.application.routes.draw do
  resources :center_names do
    get :load_center
    get :add_new_center
    get :find_center
   
  end
  resources :user_details do 
    get :approve_user, on: :member
  end
  resources :group_benefits
  resources :group_premia
  resources :branches do
    get :load_branch
  end
  devise_for :users
  resources :premium_rates
  
  resources :members do
    collection do
      post :import
    end
  end

  resources :coverages do
    get :selected, on: :member
    patch :sgyrt_submit, on: :member # This is a PATCH route
    patch :lppi_submit, on: :member
    # get :sgyrt_submit, on: :member # This is a GET route
    get :check_residency
    get :coverage_history
    get :coverage_premium_benefits
    get :individual_only
    get :group_only
    collection do
      get :loan
      get :renewal
    end
  end
  
  resources :dependents do
    get :age_validation
    collection do
      post :import
    end
  end

  resources :batches do
    get :unlisted_preview, on: :member
    get :batch_submit, on: :member
    get :batch_download, on: :member
    get :batch_preview, on: :member
    get :load_batch
    get :find_batch
    get :add_new_batch
    collection do
      post :import
    end
    member do 
      get :import_cov
    end
    # post :import_coverages, on: :member
  end


  resources :benefits
  resources :posts

  # resources :coverages do
  #   get :selected, on: :member
  # end

  #get 'pages/home'
  #get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-secondary text-warning">
  <!-- Copyright -->
  <div class="text-center p-3">
    © 2020 Copyright:
    <a class="text-light" href="https://1cisp.coop">1CISP.coop</a>
    
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom py-3">
    <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <a class="navbar-brand center" href="#">
        <%= image_tag 'pmfc.png', width: 100, class: 'mb-2 mb-lg-0 me-2' %>
      </a>
      <a class="navbar-brand text-success" href="#">PMFC</a>
        <% if user_signed_in? %> 
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="<%= batches_url %>">Loans</a></li>
            <li class="nav-item"><a class="nav-link" href="<%= members_url %>">Members</a></li>
          <% if current_user.admin? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Data Entries</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="<%= group_benefits_url %>">Group Benefits</a></li>
                <li><a class="dropdown-item" href="<%= group_premia_url %>">Group Premium</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="<%= branches_url %>">Branch</a></li>
                <li><a class="dropdown-item" href="<%= benefits_url %>">Benefits</a></li>
                <li><a class="dropdown-item" href="<%= center_names_url %>">Center Name</a></li>
                <li><a class="dropdown-item" href="<%= user_details_url %>">Users</a></li>
              </ul>
            </li>
        <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Data Entries</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="<%= center_names_url %>">Center Name</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="<%= branches_url %>">Branch</a></li>
              </ul>
            </li>
        <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle"></i> Hi, <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
              <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-primary mx-2" %></li>
            </ul>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>

<%# console %>

app/views/layouts/_notification.html.erb
<% flash.each do |flash_type, message| %>
  <div class="toast-container position-absolute top-0 end-0 pe-3 pt-3">
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header text-white bg-<%= flash_type == 'notice' ? 'success' : 'danger' %>" >
        <strong class="me-auto"><%= flash_type == 'notice' ? 'Notice' : 'Alert' %></strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
            <%= message.html_safe %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PMFC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.0.3/dist/css/tom-select.css" rel="stylesheet">
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet">

    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "jquery" %>
  </head>

  <body class="d-flex flex-column">
   
      <%= render "layouts/navbar" if user_signed_in? %>
  
    <div class="container mt-3">
      <div class="row d-flex justify-content-center">
        <div id="flash" style="width: auto" remote_modal>
          <%= render "layouts/notification" %>
        </div>
      </div>
     
      <%= yield %>
      <%= turbo_frame_tag "remote_modal", target: "_top" %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>