config/routes.rb
Rails.application.routes.draw do
  resources :center_names do
    get :load_center
    get :add_new_center
    get :find_center
   
  end
  resources :user_details do 
    get :approve_user, on: :member
  end
  resources :group_benefits
  resources :group_premia
  resources :branches do
    get :load_branch
  end
  devise_for :users
  resources :premium_rates
  
  resources :members do
    collection do
      post :import
    end
  end

  resources :coverages do
    get :selected, on: :member
    patch :sgyrt_submit, on: :member # This is a PATCH route
    patch :lppi_submit, on: :member
    # get :sgyrt_submit, on: :member # This is a GET route
    get :check_residency
    get :coverage_history
    get :coverage_premium_benefits
    get :individual_only
    get :group_only
    collection do
      get :loan
      get :renewal
    end
  end
  
  resources :dependents do
    get :age_validation
    collection do
      post :import
    end
  end

  resources :batches do
    get :unlisted_preview, on: :member
    get :batch_submit, on: :member
    get :batch_download, on: :member
    get :batch_preview, on: :member
    get :load_batch
    get :find_batch
    get :add_new_batch
    collection do
      post :import
    end
    member do 
      get :import_cov
    end
    # post :import_coverages, on: :member
  end


  resources :benefits
  resources :posts

  # resources :coverages do
  #   get :selected, on: :member
  # end

  #get 'pages/home'
  #get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/member.rb
class Member < ApplicationRecord
  validates_presence_of :last_name, :first_name, :middle_name, :birth_date, :civil_status, :gender
  has_many :dependents, dependent: :destroy
  accepts_nested_attributes_for :dependents, reject_if: :all_blank, allow_destroy: true

  has_many :coverages, dependent: :destroy
  has_many :batches, through: :coverages
  belongs_to :branch

  def get_cmember
    "#{last_name.capitalize}" + ", " + "#{first_name.capitalize}" + " " + "#{middle_name[0.1]}" + ". " + "#{suffix}"
  end

  def to_s 
     "#{first_name}" + " " + "#{middle_name[0.1]}." + " " + "#{last_name}" + "#{suffix}"
  end
  
  def get_formatted_bday
    bday = birth_date.strftime("%m/%d/%Y")
  end

  def get_formatted_membership
    bday = date_membership.strftime("%m/%d/%Y")
  end

  def format_bday(bday)
    bday.strftime("%m/%d/%Y")
  end

  def compute_member_age(bday)
    today = Date.today
    cm_age = ((today - bday.to_date) / 365).round
    "#{cm_age}" + " y/o"
  end

  def compute_cmmbrage(efdate,bday)
    cc_mage = ((efdate.year - bday.year)).round
    "#{cc_mage}" + " y/o"
  end

  def count_dependent
    mmbr_id = id
    cdpndnt = Dependent.where(member_id: mmbr_id).count
  end

  def alpharray(val)
    numalpha = Array["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    return numalpha[val-1]
  end
  
  def self.get_members_index(admin, query, current_user)
    if query.present? == true
      if admin == true
        where("last_name LIKE ?", "%#{query}%").limit(25)
      else
        where(branch_id: current_user.user_detail.branch_id).where("last_name LIKE ? OR first_name LIKE ?", "%#{query}%", "%#{query}%").limit(25)
      end
    else
      if admin == true
        all
      else
        where(branch_id: current_user.user_detail.branch_id).limit(100)
      end
    end
  end

  def self.load_members(current_user)
    where(branch_id: current_user.user_detail.branch_id)
  end


end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    require 'pagy/extras/bootstrap'

    @members = Member.get_members_index(current_user.admin, params[:query], current_user)

    #set pagination
    @pagy, @members = pagy(@members, items: 10)
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    # @ulist = params[:unlisted]
    # @member = Member.new
    #   if @ulist.present? == true
    #     @member.last_name = @ulist[0]
    #     @member.first_name = @ulist[1]
    #     @member.middle_name = @ulist[2]
    #     @member.birth_date = @ulist[3].to_s
    #   else
    #     if Rails.env.development?
    #       dummy_data
    #     end
    #   end

    @member = Member.new
    if Rails.env.development?
      dummy_data
    end
    
  end

  def dummy_data 
    @member.last_name = FFaker::Name.last_name
    @member.first_name = FFaker::Name.first_name
    @member.middle_name = FFaker::Name.first_name[0]
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)
    @member.branch = current_user.user_detail.branch

    respond_to do |format|
      #raise "errors"
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    brn_id = current_user.user_detail.branch_id

    import_service = ImportService.new(:member, params[:file],brn_id)
    import_message = import_service.import
    # redirect_to members_path, notice: import_message

    if import_message.present? && import_message == "No file uploaded"
      flash[:notice] = "No file uploaded"
      redirect_to members_path
    else
      status_names = import_message.map do |r|
        lname = r["LASTNAME"].upcase
        fname = r["FIRSTNAME"].upcase
        mname = r["MI"].upcase
      end.compact 

      status_count = import_message.group_by { |message| message["STATUS"] }.map { |status, messages| [status, messages.size] }.to_h
      
      # raise "errors"

      flash_existing = status_count["Existing"]
      flash_uploaded = status_count["Uploaded"]

      flash_names = status_names.map { |status_names| "#{status_names}<br>" }.join
    
      flash[:notice] = "Import successful. <br><br> Existing :"+flash_existing.to_s+"<br> Uploaded :"+flash_uploaded.to_s
      redirect_to members_path
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:last_name, :first_name, :middle_name, :suffix, :birth_date, :civil_status, :gender, :mobile_no, :email,:health_declaration, :branch_id, :plan_lppi, :plan_sgyrt, dependents_attributes: [:id, :member_id, :last_name, :first_name, :middle_name, :birth_date, :relationship, :_destroy] )
    end

end

app/helpers/members_helper.rb
module MembersHelper
  def generate_member_id
    time = Time.new 
    time.strftime("%m-%d%Y%I%M%LM") 
  end

  def status
    "Test"
  end

end

app/views/members/_dependent_fields.html.erb
<div class="nested-fields">
    <div class="row">
        <%= f.input :last_name, wrapper_html: { class: "col-md-4" } %>
        <%= f.input :first_name, wrapper_html: { class: "col-md-4" } %>
        <%= f.input :middle_name, wrapper_html: { class: "col-md-4" } %>
    </div>
    <br>
    <div class="row">
        <div>
            <%= f.label :birth_date %>
            <%= f.date_field :birth_date %>
        </div>
        
        <!--<div class="col-md-6"><%# f.input :relationship %></div>-->
       
        <%= f.input :relationship, collection: ['Spouse', 'Child', 'Parent', 'Sibling'], wrapper_html: { class: "col-md-4" } %>
        <%= f.input :civil_status , collection: ['Single', 'Married', 'Widowed', 'Divorced'], include_blank: true, wrapper_html: { class: "col-md-4" } %>
        <%= f.input :gender , collection: [['Male','M'],['Female','F']], include_blank: true, wrapper_html: { class: "col-md-4" } %>
        
    </div>

    <br>
    <br>
    <%= link_to_remove_association "remove dependent", f, class:"btn btn-secondary btn-sm" %>
</div>
<br>
<br>

app/views/members/_form.html.erb
<%# @member.id.present? %>
<%# @ulist.present? %>
<%#= simple_form_for(@member, data: { controller: "flatpickr" }) do |f| %>
<%= simple_form_for(@member) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="container" data-controller="flatpickr" data-select-url="<%= members_path() %>">
  <div class="form-inputs">
    
    <!--Select-->
    <% if current_user.admin? %>
      <%= f.association :branch, label: "Branch", input_html: { data: { controller: 'ts--select' } } %>
    <% else %>
      <%= f.association :branch, collection: Branch.where(id: current_user.user_detail.branch_id), label: "Branch", input_html: { data: { controller: 'ts--select' } }, selected: Branch.where(id: current_user.user_detail.branch_id)  %>
    <% end %>
    <!--Select-->

    <div class="row">
      <%= f.input :last_name, wrapper_html: { class: "col-md-4" } %>
      <%= f.input :first_name, wrapper_html: { class: "col-md-4" } %>
      <%= f.input :middle_name, label: "M.I", wrapper_html: { class: "col-md-2" } %>
      <%= f.input :suffix, wrapper_html: { class: "col-md-2" } %>
    </div>
    
    <!--Date-Picker-->
    <div class="row">
      <div class="col-md-6">
        <%= f.label :birth_date %>
        <%= f.date_field :birth_date, class: "#bdate_pick" %>
      </div>
      <!--<div class="col-md-6">
        <%#= f.label :date_membership %>
        <%#= f.date_field :date_membership, class: "dmdate_pick" %>
     </div>-->
    </div><br>
    <!--Date-Picker-->
    
    <div class="row">
      <% if @member.gender.present? == true %>
        <% mgender = @member.gender[0] %>
        <%= f.input :civil_status , collection: ['Single', 'Married', 'Widowed', 'Divorced'], include_blank: true, wrapper_html: { class: "col-md-6" } %>
        <%= f.input :gender, collection: [['Male','M'],['Female','F']], selected: mgender, include_blank: true, wrapper_html: { class: "col-md-6" } %>
      <% else %>
        <%= f.input :civil_status , collection: ['Single', 'Married', 'Widowed', 'Divorced'], include_blank: true, wrapper_html: { class: "col-md-6" } %>
        <%= f.input :gender, collection: [['Male','M'],['Female','F']], include_blank: true, wrapper_html: { class: "col-md-6" } %>  
      <% end %>
    </div>
    
    <div class="row">
      <%= f.input :mobile_no, wrapper_html: { class: "col-md-6" } %>
      <%= f.input :email, wrapper_html: { class: "col-md-6" } %>
    </div>
    <div class="row"><%= f.input :health_declaration, wrapper_html: { class: "col-md-12" } %></div>

    <!--Plan-Activation-->
    <%# if current_user.admin == true %>
    <div class="card">
      <h3 class="card-header">Plan</h3>
      <div class="card-body">
        <div class="row">
          <%= f.input :plan_lppi, label: "LPPI", wrapper_html: { class: "col-md-6" } %>
          <%= f.input :plan_sgyrt, label: "SGYRT", wrapper_html: { class: "col-md-6" } %>
          <%#= f.check_box :plan_lppi, data: { action: "flatpickr#toggle" } %>
        </div>
      </div>
    </div>
    <%# end %>
    <!--Plan-Activation-->
    <br>
    <!--Nested-Cocoon-->
    <div class="card">
      <h3 class="card-header">Dependents</h3>
      <div class="card-body">
        <div id="dependents">
          <% f.simple_fields_for :dependents do |dependent| %>
            <%= render "dependent_fields", f: dependent %>
          <% end %>
        </div>
      <div class="links">
        <%= link_to_add_association "add dependent", f, :dependents, class:"btn btn-secondary btn-sm" %>
      </div>
    </div>
    </div>
    <!--Nested-Cocoon-->
  </div>
  <br>
  <br>
  <div class="form-actions">
    <%#= link_to '<i class="bi bi-arrow-bar-left"></i>'.html_safe, members_path, class: "btn btn-secondary" %>
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/members/_member.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="mt-4 p-5 bg-secondary text-white rounded" id="<%= dom_id member %>">
      <h1 class="text-truncate"><%= member.get_cmember %></h1>
      <div class="text-wrap fw-lighter"><strong>Birth date: </strong><%= "#{member.get_formatted_bday} | ("+"#{member.compute_member_age(member.birth_date)})" %></div>
      <!--<div class="text-wrap fw-lighter"><strong>Date membership: </strong><%# member.get_formatted_membership %></div>-->
      <div class="text-wrap fw-lighter"><strong>Civil status: </strong><%= member.civil_status %></div>
      <div class="text-wrap fw-lighter"><strong>Gender: </strong><%= member.gender %></div>
      <div class="text-wrap fw-lighter"><strong>Mobile no: </strong><%= member.mobile_no %></div>
      <div class="text-wrap fw-lighter"><strong>Email: </strong><%= member.email %></div>
      <% 
        hstatus = member.health_declaration
        if !hstatus.nil? && hstatus.size > 3  
      %>
          <div class="text-wrap fw-lighter">Health Declaration: <strong>(<%= member.health_declaration %>)</strong></div>
      <% end %>
    </div>
  </div>
  <div class="col-lg-12">
    <%# content_tag :h4, "List of Dependents" %>
    <div class="card-body">
      <%= link_to '<i class="bi bi-arrow-bar-left"></i>'.html_safe, members_path, class: 'btn btn-primary btn-sm' %> |
      <%= link_to new_dependent_path(m: member), class: 'btn btn-primary btn-sm' do %> New Dependent <% end %> | 
      <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_member_path(@member), data: { turbo_frame:"remote_modal" }, class: 'btn btn-primary btn-sm' %> |
      <%= link_to '<i class="bi bi-trash"></i>'.html_safe, @member, class: 'btn btn-danger btn-sm', method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
    </div>
  </div>
  <!--Coverage-->
  <div class="col-lg-8">
    <% if member.coverages.present? %>
    <div class="accordion" id="accordionExample">
      <% 
        member.coverages.each do |mcb| 
          loan_prem = mcb.loan_premium 
          group_prem = mcb.group_premium 
          
          cterm = mcb.term
          cbatch = mcb.batch.title

          gblife = mcb.group_benefit.life
          gbadd = mcb.group_benefit.add
          gbburial = mcb.group_benefit.burial

          dependent_cvg = mcb.dependent_coverages.count(:id)
          dependent_prem = mcb.dependent_coverages.sum(:premium)
          mmbr_aging = Coverage.new(effectivity: mcb.effectivity, expiry: mcb.expiry)
          m_aging = mmbr_aging.coverage_aging
      %>
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne-<%= "#{mcb.batch_id}" %>" aria-expanded="true" aria-controls="collapseOne">
            <%= "#{mcb.batch.title} "+" (#{mcb.batch.created_at.strftime("%Y")})"+" (#{mcb.coverage_status})" %>
            <% if m_aging == 0 %>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">Expired</span>
            <% else %>
            <span class="position-absolute top-0 start-100 translate-middle badge bg-secondary"><%= "#{m_aging}"+" day(s)" %></span>
            <% end %>
          </button>
        </h2>
        <% if m_aging == 0 %>
        <div id="collapseOne-<%= "#{mcb.batch_id}" %>" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <% else %>
        <div id="collapseOne-<%= "#{mcb.batch_id}" %>" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <% end %>  
          <div class="accordion-body">
            <table class="table table-striped table-bordered table-hover table-sm">
              <thead>
                <tr>
                  <th class="text-center" width="5%"><%= mcb.id %></th>
                  <th>
                    <div class="text-center text-wrap fw-bold text-muted"><small><%= cbatch %></small></div>
                  </th>
                  <th>
                    <div class="badge bg-primary text-wrap" style="width: 10rem;"><%= mcb.coverage_date %></div>
                    <div class="badge bg-primary text-wrap" style="width: 2rem;"><%= cterm %></div>
                    <div class="badge bg-primary text-wrap" style="width: 4rem;"><%= mcb.coverage_status %></div>
                  </th>
                  <th class="text-center">
                    <%= link_to '<i class="bi bi-eye-fill"></i>'.html_safe+" View", coverage_path(mcb.id, activeID: nil), class: 'btn btn-secondary btn-sm', data: {turbo_frame: "remote_modal"} %>
                  </th>
                </tr>
              </thead>
            </table>
            <!--Coverage-->

            <!--Coverage-->
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% else %>
    <h3 class="text-truncate">No record(s) found...</h3>
    <% end %>
  </div>
  <!--Coverage-->

  <!--Dependent-Info-->
    <div class="col-lg-4">
      <table class="table table-striped table-bordered table-hover table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Dependent Info</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% 
          dpdntid = 0
          dpdntcount = 0
          dpprm = 0
        if @member.dependents.present?
            @member.dependents.each do |dependent| 
            dpdntcount += 1
            dpdntid = dependent.id
        %>
        <tr>
          <th scope="row"><%# dpdntid %><%= dpdntcount %></th>
          <td>
            <div class="text-wrap fw-lighter"><small><%= "#{dependent} ("+"#{dependent.relationship})" %></small></div>
          </td>
          <td>
            <%= link_to '<i class="bi bi-eye-fill"></i>'.html_safe, dependent_path(dependent), class: 'btn btn-secondary btn-sm', data: { turbo_frame: "remote_modal"} %>
            <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_dependent_path(dependent), class: 'btn btn-secondary btn-sm', data: { turbo_frame: "remote_modal"} %>
            <%= link_to '<i class="bi bi-trash"></i>'.html_safe, dependent, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          </td>
        </tr>
          <% end %>
        <% else %>
        <tr>
          <td class="text-truncate" colspan="3">No record(s) found...</td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  <!--Dependent-Info-->
  
</div>

app/views/members/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>

    <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">

            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body remote_modal_body" id="remote_modal_body">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/members/_search_member.html.erb
<%= turbo_frame_tag "members" do %>
  <% raise "errors" %>
  <%# render member %>
<% end %>

app/views/members/edit.html.erb
<!--<div class="card">
  <h5 class="card-header">Edit member</h5>
  <div class="card-body">
    ....
  </div>
</div>-->
<%= render "remote_modal", title: "Edit Member" do %>
  <%= render "form", member: @member %>
<% end %>

app/views/members/index.html.erb
<%# content_tag :h1, "List of Members" %>
<div class="card mb-3">
  <div class="card-header">Member Module</div>
  <div class="card-body">
      <div class=" row">
        <div class="col-lg-4"></div>
        <!--Upload Member-->
        <div class="col-lg-4">
          <%= form_with url: import_members_path, method: :post do |form| %>
              <%= form.label :file, "For member enrollment upload your csv file.", class: "form-text" %>
              <div class="d-flex gap-3">
                <%= form.file_field :file, class: "form-control", style: "width: 80%" %>
                <%= submit_tag 'Upload', class: "btn btn-primary btn-sm" %>
              </div>
            <% end %>
        </div>
        <!--Upload Member-->
        <div class="col-lg-4"></div>
      </div> 
    </div> 
</div>

<div class="row">
<!--Search-->
  <div class="col-lg-12">
    <%= form_with( url: members_path, method: :get, data: {turbo_frame: "search_member"} ) do |form| %>
    <div class="input-group mb-3">
      <%= form.text_field :query, placeholder: 'Search by last name...', class: "form-control" %>
      <%= form.submit 'Search', class: "btn btn-success" %>
      <!--Add Member-->
      <%= link_to new_member_path, data: { turbo_frame:"remote_modal" }, class: 'btn btn-primary' do %> New Member <% end %>
      <!--Add Member-->
      <!--Add Dependent-->
      <%= link_to 'Add Dependent <i class="bi bi-arrow-bar-right"></i>'.html_safe, dependents_path, class: "btn btn-secondary" %>
      <!--Add Dependent-->
    </div>
    <% end %>
      <%== pagy_bootstrap_nav(@pagy) %>
      <%== pagy_info(@pagy) %>
  </div>
<!--Search-->
  <div class="col-lg-12">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Member Info</th>
          <th>Coverage</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% 
        if @members.present?
          @members.each do |member| 
        
        %>
        <tr class="table-secondary" id="members">
          <th><%= member.id %></th>
          <td>
          <% 
            dpcount = member.count_dependent
            hstatus = member.health_declaration
          %>
            <% if dpcount > 0 %>
            <div class="text-wrap fw-bold">
              <strong><%= member.get_cmember.upcase %></strong>
              <span class="badge bg-secondary">Principal</span>
              <!--Health declaration status-->
              <% if !hstatus.nil? && hstatus.size > 3 %>
                <span class="bi bi-clipboard2-pulse-fill"></span>
              <% end %>
              <!--Health declaration status-->
            </div>
            <% else %>
            <div class="text-wrap fw-bold"><strong><%= member.get_cmember.upcase %></strong></div>
            <% end %>
            <div class="text-wrap fw-light"><small>Coverage availed: <%= member.coverages.count %> | Residency: <%= member.coverages.sum(:term) %></small></div>
            <div class="text-wrap fw-light">
              <% if member.plan_lppi? == true %>
              <small><i class="bi bi-file-text"></i> LPPI: <%= '<i class="bi bi-check-lg"></i>'.html_safe %></small>
              <% elsif member.plan_lppi? == false %>
              <small><i class="bi bi-file-text"></i> LPPI: <%= '<i class="bi bi-x-lg"></i>'.html_safe %></small>
              <% end %>
              <% if member.plan_sgyrt? == true %>
              <small><i class="bi bi-file-text"></i> SGYRT: <%= '<i class="bi bi-check-lg"></i>'.html_safe %></small>
              <% elsif member.plan_sgyrt? == false %>
              <small><i class="bi bi-file-text"></i> SGYRT: <%= '<i class="bi bi-x-lg"></i>'.html_safe %></small>
              <% end %>
            </div>
          </td>
          <td>
            <%# member.coverages.each do |mcb| %>
            <% member.coverages.order(created_at: :desc).limit(1).each do |mcb| %>
              <div class="text-wrap fw-light"><i class="bi bi-receipt-cutoff"></i> <small><%= mcb.batch.title %></small></div>
              <div class="text-wrap fw-light"><i class="bi bi-calendar"></i> 
                <small><%=  "#{to_shortdate(mcb.effectivity)+" - "+to_shortdate(mcb.expiry)}" %></small>
              </div>
              <div class="text-wrap fw-light"><i class="bi bi-calendar3"></i> 
                <small>
                  <% cvg_aging = mcb.coverage_aging %>
                  <%= mcb.coverage_aging_status(cvg_aging) %>
                </small>
              </div>
            <% end %>
          </td>
          <td>
          <% if current_user.admin == true %>
            <%= link_to '<i class="bi bi-eye-fill"></i>'.html_safe, member, class: 'btn btn-secondary btn-sm ' %>
            <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_member_path(member), data: { turbo_frame:"remote_modal" }, class: 'btn btn-secondary btn-sm' %>
            <%= link_to '<i class="bi bi-trash"></i>'.html_safe, member, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          <% else %>
            <%= link_to '<i class="bi bi-eye-fill"></i>'.html_safe, member, class: 'btn btn-secondary btn-sm ' %>
            <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_member_path(member), data: { turbo_frame:"remote_modal" }, class: 'btn btn-secondary btn-sm' %>
            <% link_to '<i class="bi bi-trash"></i>'.html_safe, member, class: "btn btn-danger btn-sm", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
          <% end %>
          </td>
        </tr>
        <%
          mdcount = 0 
          member.dependents.each do |md| 
            mdcount += 1
        %> 
        <tr class="table-info">
          <td></td>
          <td colspan="3">
            <div class="text-wrap fw-light text-muted">
              <small><%= "#{member.alpharray(mdcount)}. "+md.full_name %><span class="badge bg-muted text-dark">Dependent</span></small>
            </div>
          </td>
        </tr>
        <% end %>
      <% end %>

      <% else %>

        <tr>
          <td colspan="4">No record(s) found...</td>
        </tr>

      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/members/new.html.erb
<!--<div class="card">
    <h5 class="card-header">Add member <%# current_user.user_detail.last_name %><%# current_user.user_detail.branch_id %></h5>
    <div class="card-body">
      ....
    </div>
  </div>-->
<% if @ulist.present? == true %>
  <div class="card">
    <h5 class="card-header">Add member <%# current_user.user_detail.last_name %><%# current_user.user_detail.branch_id %></h5>
    <div class="card-body">
      <%= render "form", item: @item %>
    </div>
  </div>
<% else %>
  <%= render "remote_modal", title: "Add Member" do %>
      <%= render "form", item: @item %>
  <% end %>
<% end %>

app/views/members/show.html.erb
<%= render @member %>
<br>
<!--<div>
  <%# link_to "Edit", edit_member_path(@member), class: 'btn btn-primary' %> |
  <%# link_to "Back", members_path, class: 'btn btn-primary' %> |
  <%# link_to "Delete", @member, class: 'btn btn-danger', method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
</div>-->
<br>